name: autoGreen

on:
  push:
    branches:
      - master
  schedule:
    - cron: "20 18 * * *"

jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Auto green
        run: |
          git config --local user.email "tiffanyzhang2015@foxmail.com"
          git config --local user.name "aluck-Tiffany"
          git remote set-url origin https://github.com/aluck-Tiffany/test-rail-example.git
          git pull --rebase
          git commit --allow-empty -m "a commit a day to test this yml"
          git push
